--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.4
-- Dumped by pg_dump version 9.3.4
-- Started on 2014-07-30 06:03:51 WIB

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = sanad, pg_catalog;

--
-- TOC entry 2015 (class 0 OID 17270)
-- Dependencies: 173
-- Data for Name: property; Type: TABLE DATA; Schema: sanad; Owner: postgres
--

INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'bd520f26-a0e0-49f3-bf3d-506326af306d', 'yang benar taqobbalallahu (تقبل الله منا ومنكم)', 'yang benar taqobbalallahu', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '7e004ecb-ed73-478a-b5e2-a1702114f9e1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'c4fd2bac-bf31-43ae-bd21-083d65b4e828', 'yang benar taqobbalallahu (تقبل الله منا ومنكم)', 'yang benar taqobbalallahu (تقبل الله منا ومنكم)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '79f2561d-f62d-4faa-a738-fa0d5fef26ca', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '52d1dac6-4eda-4b76-88b9-8f55805ca658', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '9efaaba2-2e62-4d96-a819-6b091968ebb8', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'b1726e32-d980-441b-a05d-95d218aeb96a', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '48473b3b-b08f-4736-9af4-b1d094481e15', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '264e8bfd-ac56-4706-96f2-4fa743b43339', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '4edb0202-8a22-4760-844b-5ab717304a85', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '46e1cfa2-b9b8-41bb-a342-9e00121536a3', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '68198d22-2405-4ddf-9af7-d19c92e124e0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '3c9fde25-5a73-468e-a603-12f068da4d63', 'lafadznya من العائدين و الفائزين', 'lafadznya من العائدين و الفائزين', NULL, NULL, 'OFFICIAL', NULL, NULL, NULL, NULL, NULL, NULL, '062c30d8-bcb3-47d2-9b33-dd471223e4d1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '75e6e8e5-703d-48f9-8be3-32aef653260e', 'lafadznya من العائدين و الفائزين', 'lafadznya من العائدين و الفائزين', NULL, NULL, 'OFFICIAL', NULL, NULL, NULL, NULL, NULL, NULL, 'b5755e1a-a4e3-43df-94dd-a6162c75757a', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '48ef7e8d-c0fe-4f0b-ad78-4dd7c375c986', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, 'd7afce14-db03-4c29-bdda-579fa3e964f0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '67de6b5e-d5d8-41bc-8570-821a6b69826f', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '85074910-89b8-4ebb-9901-9e20ac78fafa', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '0bb89693-5aed-4e73-83cd-7dd337ce0a48', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '7daf6a6a-b704-4955-8b25-2dc55c2f057f', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'da32d871-c4e4-4b5c-992a-f217fc359084', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, 'f258c108-a225-4a11-80dd-48a21854b5f2', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'd0f9533e-72b5-491c-b8e5-e22a42b6bef3', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, 'ca3b2167-93a8-41a6-9fda-d20dc319b068', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'bb8e6732-c05d-4949-a778-d274e4b6239c', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '538a8de5-d943-41dd-b740-c764e6d6bc3f', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '12377f61-3bf7-41de-872d-7ad3bf4f815e', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '5d288eab-8711-4e89-a772-1a99d77908e4', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'd609e326-e18a-4ae1-a90f-999972a06d70', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '78cf2aa5-3625-446e-8edd-f551a639925d', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '40987059-cf3b-4715-9c3b-692e31b25f49', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, 'fb53ae68-3cd9-472d-b935-a4003246383a', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '1c707895-5f7c-4c66-8c93-2dfc5b493ba8', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '4b196e4e-6be8-4561-9678-0c32b12014a4', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '6c60330e-ffd1-4c9e-b78c-7a3eeab9c9c2', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '7d486b6a-bd6f-4cd4-8166-842b2355ee90', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'f4317c29-938b-48c3-9084-1a25fcb9870d', 'lafadznya تقبل الله منا ومنكم', 'lafadznya تقبل الله منا ومنكم', NULL, NULL, 'FORMAL', NULL, NULL, NULL, NULL, NULL, NULL, '6716d949-cfde-4911-8efc-d058a286b1f5', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '65a61ce1-8c2b-45d3-bd1a-5fe30910d5cd', 'lafadznya تقبل الله منا ومنكم', 'lafadznya تقبل الله منا ومنكم', NULL, NULL, 'FORMAL', NULL, NULL, NULL, NULL, NULL, NULL, 'ff146997-b5c3-4572-bf3b-12537cf9da98', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '47deb267-1621-4617-b25d-a422e119959e', 'perhatikan ba dobel: taqoBBalallahu (تقبل الله منا ومنكم)', 'perhatikan ba dobel: taqoBBalallahu (تقبل الله منا ومنكم)', NULL, NULL, 'CASUAL', NULL, NULL, NULL, NULL, NULL, NULL, '022ca10b-0944-4dba-989d-43b6b9e0041b', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '8f8fcd31-f96e-4692-9cee-9b68d0d1d98f', 'perhatikan ba dobel: taqoBBalallahu (تقبل الله منا ومنكم)', 'perhatikan ba dobel: taqoBBalallahu (تقبل الله منا ومنكم)', NULL, NULL, 'CASUAL', NULL, NULL, NULL, NULL, NULL, NULL, 'e5599c27-89ad-483b-b0cf-a44b4f553eeb', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '71a521af-1762-4735-bfa6-3122c7f99819', 'yang benar taqobbalallahu (تقبل الله منا ومنكم)', 'yang benar taqobbalallahu (تقبل الله منا ومنكم)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '81fb53a3-6962-4da3-950f-84d7dfee4da5', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', '946467e5-cb71-4bf6-a229-89c7f04cc84e', 'yang benar taqobbalallahu (تقبل الله منا ومنكم)', 'yang benar taqobbalallahu (تقبل الله منا ومنكم)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '2d0e4419-5aa0-4bbc-8664-6aa36abaef09', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO property (dtype, id, description, descriptionhtml, personid, thingkind, spelling, adoc, html, successivity, scholarid, authenticity, thing_id, transliteration_id, literal_id, articlebodies_thing_id, successivities_thing_id, names_thing_id, authors_thing_id, authenticities_thing_id) VALUES ('SpellingProperty', 'a9906ee1-1420-4db7-ba5c-a6ec213b9c78', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', 'yang benar: minal ''aidin wal faizin (من العائدين و الفائزين)', NULL, NULL, 'WRONG', NULL, NULL, NULL, NULL, NULL, NULL, '892a3738-6eb5-4b3a-9d8f-46ef00ee5122', NULL, NULL, NULL, NULL, NULL, NULL);


-- Completed on 2014-07-30 06:03:51 WIB

--
-- PostgreSQL database dump complete
--

